language: r
cache: packages
sudo: required

matrix:
  include:
   - os: linux
     compiler: gcc 
     addons: 
       apt:
         sources: ['ubuntu-toolchain-r-test']
         packages: ['g++-5']
     env:
      - COMPILER=g++-5
      - CC=gcc-5
      - CXX=g++-5
      - FC=gfortran-5
      - F77=gfortran-5

before_install:
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 100
 - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-5 100
 - mkdir -p ~/.R
 - echo "VkVSPS01DQpDQz1nY2MkKFZFUikgLXN0ZD1jMTEgDQpDWFg9ZysrJChWRVIpDQpTSExJQl9DWFhMRD1nKyskKFZFUikNCkZDPWdmb3J0cmFuJChWRVIpDQpGNzc9Z2ZvcnRyYW4kKFZFUik=" | base64 -d > ~/.R/Makevars
 - cat ~/.R/Makevars

notifications:
  email:
    on_success: change
    on_failure: always
